### ISSUE TITLE
PyGObject sync

### ISSUE THREAD

**Issue by lazka** [lazka/pgi-docgen#10]
* Add stubs for GObject.Object methods where missing
* ~~Sync overrides (Gtk,GObject,Gdk missing)~~
* Include docstrings from the GTK+3 tutorial (pre merge) in the overrides/pgi core
* Push changes upstream
* ~~Remove clutter overrides (pygobject doesn't have them), port examples~~

**Comment by lazka** [comment]
We need a script to check:

* What are the differences regarding exposed attributes for all base types (GType, GError, GInterface, GObject, Paramspecs) between gi and pgi
* Which don't have docs.

**Comment by wolfv** [comment]
took me quite some time to find (or better, not find) GObject.signal_new

**Comment by lazka** [comment]
If there is still anything missing please open a new issue.

**Comment by wolfv** [comment]
Great,

thanks a lot for fixing this.

Wolf
