### ISSUE TITLE
Text inside <angle brackets> are removed

### ISSUE THREAD

**Issue by sjohannes** [lazka/pgi-docgen#101]
For example, in [Gtk.FileFilter](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/FileFilter.html#Gtk.FileFilter):

> The Gtk.FileFilter implementation of the Gtk.Buildable interface supports adding rules **using the , and elements** and listing the rules within. **Specifying a or** has the same effect as as calling Gtk.FileFilter.add_mime_type () or Gtk.FileFilter.add_pattern ().

They [should say](https://developer.gnome.org/gtk3/stable/GtkFileFilter.html#GtkFileFilter.description)

> using the &lt;mime-types>, &lt;patterns> and &lt;applications> elements
> 
> Specifying a &lt;mime-type> or &lt;pattern>

**Comment by lazka** [comment]
Thanks. Tricky.. gnome libraries currently use either markdown or docbook and they don't specify which one they use. In this case the tags get interpreted as XML as they are not escaped.
