### ISSUE TITLE
Methods overriden with strip_boolean_result show wrong return description/type

### ISSUE THREAD

**Issue by sjohannes** [lazka/pgi-docgen#102]
PyGObject overrides a number of methods that return `(success:bool, out1, out2, ...)` with `strip_boolean_result` (defined in `gi/overrides/__init__.py`), making them instead return `(out1, out2, ...)` on success and `None` on failure.

pgi-docgen doesn't seem to recognise this (or at least not all of the instances where this occurs). For example, the [`Gtk.Widget.translate_coordinates`](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.translate_coordinates) documentation indicates that it returns `(bool, int, int)`, which looks like it should be correct, except PyGObject overrides the method to return either `(int, int)` or `None` instead.

**Comment by lazka** [comment]
Related: #55

**Comment by lazka** [comment]
Fixed
