### ISSUE TITLE
Parameter documented as int instead of Gtk.IconSize

### ISSUE THREAD

**Issue by aleb** [lazka/pgi-docgen#104]
Just two examples here, but there are more (at least in Gtk.Image):
http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Button.html#Gtk.Button.new_from_icon_name
http://lazka.github.io/pgi-docs/Gtk-3.0/classes/Image.html#Gtk.Image.new_from_gicon

**Comment by lazka** [comment]
The C code is currently annotated to int so we don't get that information, not sure why.

**Comment by lazka** [comment]
This introduced the int annotations: https://bugzilla.gnome.org/show_bug.cgi?id=601425

I think the best we can do is to include the type in the argument documentation so there is a link.

**Comment by lazka** [comment]
GTK+ bug: https://bugzilla.gnome.org/show_bug.cgi?id=757411

**Comment by lazka** [comment]
Fix pushed to gtk+ master, so it will be in 3.20

**Comment by aleb** [comment]
Thanks!
