### ISSUE TITLE
link creation fail

### ISSUE THREAD

**Issue by aleb** [lazka/pgi-docgen#105]
http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TextView.html#Gtk.TextView
"[text widget conceptual overview][TextWidget]" should be a link.
For example in https://developer.gnome.org/gtk3/stable/GtkTextView.html it's a link to https://developer.gnome.org/gtk3/stable/TextWidget.html
Better link to this website than not linking at all.

**Comment by lazka** [comment]
1) We don't parse markdown atm..
2) The target of the link in question isn't available in the gir, only documentation in the C source which is directly linked to a symbol ends up there.

**Comment by gbtami** [comment]
Another one on http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Label.html#Gtk.Label.set_markup
[PangoMarkupFormat] occurs in several places. It should be a link to http://developer.gnome.org/pango/stable/PangoMarkupFormat.html
as it is at the bottom on http://python-gtk-3-tutorial.readthedocs.org/en/latest/label.html

**Comment by lazka** [comment]
Thanks. The question is how do I get from "PangoMarkupFormat" to "http://developer.gnome.org/pango/stable/PangoMarkupFormat.html"

**Comment by gbtami** [comment]
Thx!
