### ISSUE TITLE
Link to source

### ISSUE THREAD

**Issue by aleb** [lazka/pgi-docgen#106]
Would be very useful at times to look at the source of the method, because the documentation is not always the best, or just for fun. Would it be possible to have a link at Gtk.Widget.grab_focus to https://git.gnome.org/browse/gtk+/tree/gtk/gtkwidget.c#n8101 ?

**Comment by lazka** [comment]
Interesting idea.

Given a debug build (or the debian debug symbols in this case) of gtk using 
```
nm --line-numbers /usr/lib/debug/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.1800.2
```
we get the line number and absolute source path for each symbol.

For integrating it in sphinx maybe https://sphinx.readthedocs.org/en/latest/ext/linkcode.html can help.

**Comment by lazka** [comment]
meh.. as always it doesn't work in all cases... for example the Gtk.Widget.grab_focus you mentioned doesn't have any source info in the debug build, no ideas why.. grr

**Comment by lazka** [comment]
looks like a bug in "nm", I can see the line number in the dwarf data

**Comment by lazka** [comment]
https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.grab_focus
