### ISSUE TITLE
Bad links in Hierarchy

### ISSUE THREAD

**Issue by aleb** [lazka/pgi-docgen#130]
http://lazka.github.io/pgi-docs/#GES-1.0/hierarchy.html
Notice the Gst.Object link is: 
http://lazka.github.io/Gst-1.0/classes/Object.html#Gst.Object
when it should have been:
http://lazka.github.io/pgi-docs/Gst-1.0/classes/Object.html#Gst.Object

**Comment by lazka** [comment]
Weird, thanks.

**Comment by lazka** [comment]
I'll revert for now, looks like a sphinx bug
