### ISSUE TITLE
Signals - missing "widget" parameter?

### ISSUE THREAD

**Issue by Vaniax** [lazka/pgi-docgen#82]
Hi,

I have a little problem with the documentation. E.g. when I want to use the `draw` signal of a widget the callback has to have three parameters (with self):
```
draw(self, widget, cairo_context)
```

But browsing the docu I can only see the `cr` as the required parameter [Link](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.draw) . It seems to me that the `widget` parameter is always ommited. Is that an intented behaviour (no big deal but quite confusing when dealing with PyGObject for the first time)?

**Comment by lazka** [comment]
Fixed: https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.draw
