### ISSUE TITLE
TreeModelRow is missing docs

### ISSUE THREAD

**Issue by lazka** [lazka/pgi-docgen#86]
It's quite important for TreeModel related things, so do this one first:

https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TreeModelRow.html

**Comment by spiessbuerger** [comment]
I was also just looking at that page and wondering why it was empty. I don't think things changed too much from PyGTK:

http://www.pygtk.org/pygtk2reference/class-pygtktreemodelrow.html
http://www.pygtk.org/pygtk2reference/class-pygtktreemodelrowiter.html

What I noticed is that ```TreeModelRow.iterchildren()``` now always returns a ```Gtk.TreeModelRowIter```-object (even if there are no children) as opposed to returning ```None``` in PyGTK. Then calling ```Gtk.TreeModelRowIter.next()``` raises the ```StopIteration``` on the first iteration.
