### ISSUE TITLE
documentation for GtkSource missing?

### ISSUE THREAD

**Issue by ishankhare07** [lazka/pgi-docgen#87]
where is the documentation for GtkSource
``` python
from gi.repository import GtkSource
```

also i cannot find any documentation for ``` gi.repository```

correct me if I'm missing something

**Comment by lazka** [comment]
This? https://lazka.github.io/pgi-docs/#GtkSource-3.0

**Comment by ishankhare07** [comment]
Yes that's exactly what i wanted, thanks a lot!
I'm sorry on my part, I didn't see that search was case sensitive

**Comment by lazka** [comment]
No problem, thanks for the report.

**Comment by ishankhare07** [comment]
can you provide details of what **kwargs are given to the constructor, basically I want to bind a GtkSource.View to the Completer, if I do:
```python
completer = GtkSource.Completion()
completer.props.view = builder.get_object('my_source_view')
```
I get get an error : 
```
Warning: g_object_set_property: construct property "view" for object 'GtkSourceCompletion' can't be set after construction
```

**Comment by ishankhare07** [comment]
I figured it out myself
```python
completer = GtkSource.Completion(view=builder.get_object('my_source_view'))
```

**Comment by lazka** [comment]
Yeah. If you look at the property list: https://lazka.github.io/pgi-docs/#GtkSource-3.0/classes/Completion.html#properties the flags column contains r/w/c, "c" in this case means it can only be set during construction.

The ``**kargs`` of each GObject.Object subclass takes property keys and values.
