### ISSUE TITLE
Show the source library versions used

### ISSUE THREAD

**Issue by lazka** [lazka/pgi-docgen#93]
Either use the debian version or provide Python functions for each namespace to fetch the version using the respective public API.

**Comment by sjohannes** [comment]
I'm surprised this isn't readily available in the introspection data. To make matters worse, I think some libraries simply don't make their version numbers available programmatically (e.g. Nautilus-3.0), so you may have to rely on the Debian package version.

**Comment by lazka** [comment]
The next build should include some version numbers (feedback on visibility welcome.. I've just put them on the index for now). For modules with missing versions I'd suggest to create bug reports upstream to add some.

**Comment by lazka** [comment]
new build is up now
