### ISSUE TITLE
Add Grss to docs

### ISSUE THREAD

**Issue by ignatenkobrain** [lazka/pgi-docgen#96]
Please add https://git.gnome.org/browse/libgrss/tree/

**Comment by lazka** [comment]
I usually only build what is available in Debian and the latest release doesn't have introspection support there.

Why do you want it?

**Comment by ignatenkobrain** [comment]
Im planning to create new app in Python using this app, so would be great to have docs for it.

**Comment by lazka** [comment]
OK.

**Comment by lazka** [comment]
Here you go: https://lazka.github.io/pgi-docs/index.html#Grss-0.6

I'm not sure if it is actually usable from Python..

**Comment by ignatenkobrain** [comment]
Thanks! If it is not usable - I will fix it in upstream ;)

**Comment by lazka** [comment]
libgrss is now in debian: https://lazka.github.io/pgi-docs/#Grss-0.7
