### ISSUE TITLE
Adding the Gnm docs

### ISSUE THREAD

**Issue by timovwb** [lazka/pgi-docgen#97]
Is it possible to add the docs for Gnm (Gnumeric)? I've built them locally, but it would be nice to have them available online too.

**Comment by lazka** [comment]
https://lazka.github.io/pgi-docs/#Gnm-1.12

It wasn't included due to a missing dep (reported upstream [0]) and some pgi bugs (fixed now). 

[0] https://bugzilla.gnome.org/show_bug.cgi?id=753482
