### ISSUE TITLE
Properties not listed

### ISSUE THREAD

**Issue by aleb** [lazka/pgi-docgen#98]
http://lazka.github.io/pgi-docs/GES-1.0/classes/TitleSource.html#properties (GES 1.0 (1.4.0.0)) lists no direct properties.
For example http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-editing-services/html/GESTitleSource.html (GES 1.0 (1.5.90)) lists 10.

**Comment by lazka** [comment]
Those aren't gobject properties, they are some GES only thing.

**Comment by cfoch** [comment]
so I suppose those should be implemented as gobject properties

**Comment by aleb** [comment]
Indeed, at least in Pitivi they seem to be set using 
http://lazka.github.io/pgi-docs/#GES-1.0/classes/TrackElement.html#GES.TrackElement.set_child_property
instead of 
http://lazka.github.io/pgi-docs/#GObject-2.0/classes/Object.html#GObject.Object.set_property

Sorry for the confusion.

**Comment by lazka** [comment]
If there is a way to query those properties as ParamSpecs I can try including a special case. There is something similar for Gtk.Container using gtk_container_class_list_child_properties()

If found https://lazka.github.io/pgi-docs/#GES-1.0/classes/TrackElement.html#GES.TrackElement.list_children_properties

..but that returns an empty list(??) and needs an instance, but that's not a problem as long as it isn't an abstract class and has not mandatory construction properties.

any ideas?

**Comment by thiblahute** [comment]
The thing is that children properties are runtime dependent. It depends on the GstElement being use in the GESTrackElement.

For some of subclasses of GESTrackElement I define/explain the ones that will always be present for example:

 * http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-editing-services/html/GESVideoSource.html

 * http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-editing-services/html/GESTitleSource.html

I might be missing other subtype where we could define some statically but then for some reason you lost that part of the doc in http://lazka.github.io/pgi-docs/#GES-1.0/classes/VideoSource.html#GES.VideoSource -- it would be nice to fix that :) 

Apart from that I am not sure what could be done as it is really runtime dependent, and what the user is doing.

**Comment by thiblahute** [comment]
By the way this is how I define it:

https://phabricator.freedesktop.org/diffusion/GES/browse/master/ges/ges-video-source.c;1dc013984ba11ad195e3b39997b14894ee9f756a$25

**Comment by lazka** [comment]
> I might be missing other subtype where we could define some statically but then for some reason you lost that part of the doc in http://lazka.github.io/pgi-docs/#GES-1.0/classes/VideoSource.html#GES.VideoSource -- it would be nice to fix that :)

I think I fixed that with http://cgit.freedesktop.org/gstreamer/gst-editing-services/commit/?id=a66e6746493a644cd005f873770ca53525edfc51 but that didn't make it into a release.

I'll try to include 1.5.90 some time, but debian sid is currently broken due to the stdc++ ABI transition and I can't install anything right now.

**Comment by thiblahute** [comment]
Cool, let me know if it fixes it :)

**Comment by lazka** [comment]
It's up now, but the docbook to rest code could be improved.

**Comment by lazka** [comment]
Closing this. For doc parsing improvements see #44
